export interface Database {
  public: {
    Tables: {
      app_user_profiles: {
        Row: {
          id: string;
          email: string;
          full_name: string;
          phone_number: string | null;
          role: string;
          is_active: boolean | null;
          created_at: string | null;
          updated_at: string | null;
          facebook_url: string | null;
          linkedin_url: string | null;
          instagram_url: string | null;
          twitter_url: string | null;
          "Toastmaster since": string | null;
          "Mentor Name": string | null;
          "Toastmaster ID": string | null;
          "About": string | null;
          avatar_url: string | null;
          location: string | null;
          occupation: string | null;
          interests: string | null;
          achievements: string | null;
        };
        Insert: {
          id: string;
          email: string;
          full_name: string;
          phone_number?: string | null;
          role?: string;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
          facebook_url?: string | null;
          linkedin_url?: string | null;
          instagram_url?: string | null;
          twitter_url?: string | null;
          "Toastmaster since"?: string | null;
          "Mentor Name"?: string | null;
          "Toastmaster ID"?: string | null;
          "About"?: string | null;
          avatar_url?: string | null;
          location?: string | null;
          occupation?: string | null;
          interests?: string | null;
          achievements?: string | null;
        };
        Update: {
          id?: string;
          email?: string;
          full_name?: string;
          phone_number?: string | null;
          role?: string;
          is_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
          facebook_url?: string | null;
          linkedin_url?: string | null;
          instagram_url?: string | null;
          twitter_url?: string | null;
          "Toastmaster since"?: string | null;
          "Mentor Name"?: string | null;
          "Toastmaster ID"?: string | null;
          "About"?: string | null;
          avatar_url?: string | null;
          location?: string | null;
          occupation?: string | null;
          interests?: string | null;
          achievements?: string | null;
        };
      };
      clubs: {
        Row: {
          id: string;
          name: string;
          club_number: string | null;
          charter_date: string | null;
          created_at: string | null;
          updated_at: string | null;
          created_by: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          club_number?: string | null;
          charter_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          club_number?: string | null;
          charter_date?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          created_by?: string | null;
        };
      };
      app_club_user_relationship: {
        Row: {
          id: string;
          user_id: string;
          club_id: string;
          role: string;
          is_authenticated: boolean;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          user_id: string;
          club_id: string;
          role: string;
          is_authenticated?: boolean;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          user_id?: string;
          club_id?: string;
          role?: string;
          is_authenticated?: boolean;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      club_faq_items: {
        Row: {
          id: string;
          club_id: string;
          sort_order: number;
          question: string;
          answer: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          club_id: string;
          sort_order: number;
          question: string;
          answer: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          club_id?: string;
          question?: string;
          answer?: string;
          sort_order?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      club_profiles: {
        Row: {
          id: string;
          club_id: string;
          club_name: string | null;
          club_number: string | null;
          charter_date: string | null;
          club_status: string | null;
          club_type: string | null;
          club_mission: string | null;
          banner_color: string | null;
          city: string | null;
          country: string | null;
          region: string | null;
          district: string | null;
          division: string | null;
          area: string | null;
          time_zone: string | null;
          address: string | null;
          pin_code: string | null;
          google_location_link: string | null;
          meeting_day: string | null;
          meeting_frequency: string | null;
          meeting_start_time: string | null;
          meeting_end_time: string | null;
          meeting_type: string | null;
          online_meeting_link: string | null;
          facebook_url: string | null;
          twitter_url: string | null;
          linkedin_url: string | null;
          instagram_url: string | null;
          whatsapp_url: string | null;
          youtube_url: string | null;
          website_url: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          club_id: string;
          club_name?: string | null;
          club_number?: string | null;
          charter_date?: string | null;
          club_status?: string | null;
          club_type?: string | null;
          club_mission?: string | null;
          banner_color?: string | null;
          city?: string | null;
          country?: string | null;
          region?: string | null;
          district?: string | null;
          division?: string | null;
          area?: string | null;
          time_zone?: string | null;
          address?: string | null;
          pin_code?: string | null;
          google_location_link?: string | null;
          meeting_day?: string | null;
          meeting_frequency?: string | null;
          meeting_start_time?: string | null;
          meeting_end_time?: string | null;
          meeting_type?: string | null;
          online_meeting_link?: string | null;
          facebook_url?: string | null;
          twitter_url?: string | null;
          linkedin_url?: string | null;
          instagram_url?: string | null;
          whatsapp_url?: string | null;
          youtube_url?: string | null;
          website_url?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          club_id?: string;
          club_name?: string | null;
          club_number?: string | null;
          charter_date?: string | null;
          club_status?: string | null;
          club_type?: string | null;
          club_mission?: string | null;
          banner_color?: string | null;
          city?: string | null;
          country?: string | null;
          region?: string | null;
          district?: string | null;
          division?: string | null;
          area?: string | null;
          time_zone?: string | null;
          address?: string | null;
          pin_code?: string | null;
          google_location_link?: string | null;
          meeting_day?: string | null;
          meeting_frequency?: string | null;
          meeting_start_time?: string | null;
          meeting_end_time?: string | null;
          meeting_type?: string | null;
          online_meeting_link?: string | null;
          facebook_url?: string | null;
          twitter_url?: string | null;
          linkedin_url?: string | null;
          instagram_url?: string | null;
          whatsapp_url?: string | null;
          youtube_url?: string | null;
          website_url?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      app_club_meeting: {
        Row: {
          id: string;
          club_id: string;
          meeting_title: string;
          meeting_date: string;
          meeting_number: string | null;
          meeting_start_time: string | null;
          meeting_end_time: string | null;
          meeting_duration: string | null;
          meeting_mode: string;
          meeting_location: string | null;
          meeting_link: string | null;
          meeting_status: string;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          club_id: string;
          meeting_title: string;
          meeting_date: string;
          meeting_number?: string | null;
          meeting_start_time?: string | null;
          meeting_end_time?: string | null;
          meeting_duration?: string | null;
          meeting_mode?: string;
          meeting_location?: string | null;
          meeting_link?: string | null;
          meeting_status?: string;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          club_id?: string;
          meeting_title?: string;
          meeting_date?: string;
          meeting_number?: string | null;
          meeting_start_time?: string | null;
          meeting_end_time?: string | null;
          meeting_duration?: string | null;
          meeting_mode?: string;
          meeting_location?: string | null;
          meeting_link?: string | null;
          meeting_status?: string;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      app_meeting_roles_management: {
        Row: {
          id: string;
          meeting_id: string;
          role_id: string;
          role_name: string;
          role_metric: string;
          assigned_user_id: string | null;
          is_required: boolean | null;
          max_participants: number | null;
          order_index: number | null;
          booking_status: string | null;
          booked_at: string | null;
          withdrawn_at: string | null;
          role_status: string | null;
          role_classification: string | null;
          club_id: string;
          is_completed: boolean;
          completed_at: string | null;
          completion_notes: string | null;
          speech_title: string | null;
          speech_objectives: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          role_id: string;
          role_name: string;
          role_metric: string;
          assigned_user_id?: string | null;
          is_required?: boolean | null;
          max_participants?: number | null;
          order_index?: number | null;
          booking_status?: string | null;
          booked_at?: string | null;
          withdrawn_at?: string | null;
          role_status?: string | null;
          role_classification?: string | null;
          club_id: string;
          is_completed?: boolean;
          completed_at?: string | null;
          completion_notes?: string | null;
          speech_title?: string | null;
          speech_objectives?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          role_id?: string;
          role_name?: string;
          role_metric?: string;
          assigned_user_id?: string | null;
          is_required?: boolean | null;
          max_participants?: number | null;
          order_index?: number | null;
          booking_status?: string | null;
          booked_at?: string | null;
          withdrawn_at?: string | null;
          role_status?: string | null;
          role_classification?: string | null;
          club_id?: string;
          is_completed?: boolean;
          completed_at?: string | null;
          completion_notes?: string | null;
          speech_title?: string | null;
          speech_objectives?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      app_meeting_toastmaster_notes: {
        Row: {
          id: string;
          meeting_id: string;
          club_id: string;
          toastmaster_user_id: string;
          personal_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          club_id: string;
          toastmaster_user_id: string;
          personal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          club_id?: string;
          toastmaster_user_id?: string;
          personal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      app_meeting_timer_notes: {
        Row: {
          id: string;
          meeting_id: string;
          club_id: string;
          timer_user_id: string;
          personal_notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          club_id: string;
          timer_user_id: string;
          personal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          club_id?: string;
          timer_user_id?: string;
          personal_notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      app_agenda_management: {
        Row: {
          id: string;
          meeting_id: string;
          title: string;
          document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url: string | null;
          pdf_data: string | null;
          status: 'pending' | 'available';
          created_by: string;
          club_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          title: string;
          document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url?: string | null;
          pdf_data?: string | null;
          status?: 'pending' | 'available';
          created_by: string;
          club_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          title?: string;
          document_type?: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url?: string | null;
          pdf_data?: string | null;
          status?: 'pending' | 'available';
          created_by?: string;
          club_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      app_minutes_management: {
        Row: {
          id: string;
          meeting_id: string;
          title: string;
          document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url: string | null;
          pdf_data: string | null;
          status: 'pending' | 'available';
          created_by: string;
          club_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          title: string;
          document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url?: string | null;
          pdf_data?: string | null;
          status?: 'pending' | 'available';
          created_by: string;
          club_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          title?: string;
          document_type?: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url?: string | null;
          pdf_data?: string | null;
          status?: 'pending' | 'available';
          created_by?: string;
          club_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      app_agenda_management: {
        Row: {
          id: string;
          meeting_id: string;
          title: string;
          document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url: string | null;
          pdf_data: string | null;
          status: 'pending' | 'available';
          created_by: string;
          club_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          title: string;
          document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url?: string | null;
          pdf_data?: string | null;
          status?: 'pending' | 'available';
          created_by: string;
          club_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          title?: string;
          document_type?: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url?: string | null;
          pdf_data?: string | null;
          status?: 'pending' | 'available';
          created_by?: string;
          club_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      app_minutes_management: {
        Row: {
          id: string;
          meeting_id: string;
          title: string;
          document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url: string | null;
          pdf_data: string | null;
          status: 'pending' | 'available';
          created_by: string;
          club_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          title: string;
          document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url?: string | null;
          pdf_data?: string | null;
          status?: 'pending' | 'available';
          created_by: string;
          club_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          title?: string;
          document_type?: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
          document_url?: string | null;
          pdf_data?: string | null;
          status?: 'pending' | 'available';
          created_by?: string;
          club_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      app_meeting_feedbackcorner: {
        Row: {
          id: string;
          meeting_id: string;
          club_id: string;
          user_id: string;
          overall_rating: number;
          engagement_rating: number;
          organization_rating: number;
          environment_rating: number;
          recommendation_rating: number;
          comments: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          club_id: string;
          user_id: string;
          overall_rating: number;
          engagement_rating: number;
          organization_rating: number;
          environment_rating: number;
          recommendation_rating: number;
          comments?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          club_id?: string;
          user_id?: string;
          overall_rating?: number;
          engagement_rating?: number;
          organization_rating?: number;
          environment_rating?: number;
          recommendation_rating?: number;
          comments?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      meeting_agendas: {
        Row: {
          id: string;
          meeting_id: string;
          title: string;
          document_type: string;
          document_url: string | null;
          pdf_data: string | null;
          created_by: string;
          club_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          title: string;
          document_type: string;
          document_url?: string | null;
          pdf_data?: string | null;
          created_by: string;
          club_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          title?: string;
          document_type?: string;
          document_url?: string | null;
          pdf_data?: string | null;
          created_by?: string;
          club_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      meeting_minutes: {
        Row: {
          id: string;
          meeting_id: string;
          title: string;
          document_type: string;
          document_url: string | null;
          pdf_data: string | null;
          created_by: string;
          club_id: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          title: string;
          document_type: string;
          document_url?: string | null;
          pdf_data?: string | null;
          created_by: string;
          club_id: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          title?: string;
          document_type?: string;
          document_url?: string | null;
          pdf_data?: string | null;
          created_by?: string;
          club_id?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          message: string;
          type: string;
          is_read: boolean;
          data: any;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          message: string;
          type?: string;
          is_read?: boolean;
          data?: any;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          message?: string;
          type?: string;
          is_read?: boolean;
          data?: any;
          created_at?: string;
        };
      };
      resources: {
        Row: {
          id: string;
          club_id: string;
          title: string;
          description: string;
          resource_type: string;
          url: string | null;
          file_data: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          club_id: string;
          title: string;
          description: string;
          resource_type: string;
          url?: string | null;
          file_data?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          club_id?: string;
          title?: string;
          description?: string;
          resource_type?: string;
          url?: string | null;
          file_data?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      polls: {
        Row: {
          id: string;
          title: string;
          description: string | null;
          club_id: string;
          created_by: string;
          status: string;
          start_time: string | null;
          end_time: string | null;
          is_anonymous: boolean | null;
          allow_multiple_votes: boolean | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          description?: string | null;
          club_id: string;
          created_by: string;
          status?: string;
          start_time?: string | null;
          end_time?: string | null;
          is_anonymous?: boolean | null;
          allow_multiple_votes?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string | null;
          club_id?: string;
          created_by?: string;
          status?: string;
          start_time?: string | null;
          end_time?: string | null;
          is_anonymous?: boolean | null;
          allow_multiple_votes?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      poll_items: {
        Row: {
          id: string;
          poll_id: string;
          question_id: string;
          option_id: string;
          question_text: string;
          option_text: string;
          question_order: number | null;
          option_order: number;
          vote_count: number | null;
          is_active: boolean;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          poll_id: string;
          question_id: string;
          option_id: string;
          question_text: string;
          option_text: string;
          question_order?: number | null;
          option_order?: number;
          vote_count?: number | null;
          is_active?: boolean;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          poll_id?: string;
          question_id?: string;
          option_id?: string;
          question_text?: string;
          option_text?: string;
          question_order?: number | null;
          option_order?: number;
          vote_count?: number | null;
          is_active?: boolean;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      app_user_invitation: {
        Row: {
          id: string;
          invite_token: string;
          club_id: string;
          invitee_email: string;
          invitee_full_name: string;
          invitee_role: string;
          invited_by: string;
          status: string;
          created_at: string | null;
          expires_at: string;
          accepted_at: string | null;
          accepted_user_id: string | null;
        };
        Insert: {
          id?: string;
          invite_token: string;
          club_id: string;
          invitee_email: string;
          invitee_full_name: string;
          invitee_role?: string;
          invited_by: string;
          status?: string;
          created_at?: string | null;
          expires_at: string;
          accepted_at?: string | null;
          accepted_user_id?: string | null;
        };
        Update: {
          id?: string;
          invite_token?: string;
          club_id?: string;
          invitee_email?: string;
          invitee_full_name?: string;
          invitee_role?: string;
          invited_by?: string;
          status?: string;
          created_at?: string | null;
          expires_at?: string;
          accepted_at?: string | null;
          accepted_user_id?: string | null;
        };
      };
      speeches: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          document_type: 'google_doc';
          document_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          document_type: 'google_doc';
          document_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          title?: string;
          document_type?: 'google_doc';
          document_url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      meetings: {
        Row: {
          id: string;
          club_id: string | null;
          title: string;
          meeting_number: string | null;
          theme: string | null;
          meeting_date: string;
          meeting_time: string;
          mode: string;
          location: string | null;
          status: string;
          agenda: any | null;
          created_by: string | null;
          created_at: string | null;
          updated_at: string | null;
          minutes_status: string | null;
          agenda_status: string | null;
        };
        Insert: {
          id?: string;
          club_id?: string | null;
          title: string;
          meeting_number?: string | null;
          theme?: string | null;
          meeting_date: string;
          meeting_time: string;
          mode?: string;
          location?: string | null;
          status?: string;
          agenda?: any | null;
          created_by?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          minutes_status?: string | null;
          agenda_status?: string | null;
        };
        Update: {
          id?: string;
          club_id?: string | null;
          title?: string;
          meeting_number?: string | null;
          theme?: string | null;
          meeting_date?: string;
          meeting_time?: string;
          mode?: string;
          location?: string | null;
          status?: string;
          agenda?: any | null;
          created_by?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
          minutes_status?: string | null;
          agenda_status?: string | null;
        };
      };
      pathway_projects: {
        Row: {
          id: string;
          user_id: string;
          pathway_id: string;
          project_name: string;
          level: number;
          start_date: string;
          end_date: string | null;
          status: string;
          updated_in_portal: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          pathway_id: string;
          project_name: string;
          level: number;
          start_date: string;
          end_date?: string | null;
          status: string;
          updated_in_portal: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          pathway_id?: string;
          project_name?: string;
          level?: number;
          start_date?: string;
          end_date?: string | null;
          status?: string;
          updated_in_portal?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      pathways: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          total_levels: number;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          total_levels?: number;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          total_levels?: number;
          created_at?: string | null;
        };
      };
      simple_poll_votes: {
        Row: {
          id: string;
          poll_id: string;
          question_id: string;
          option_id: string;
          user_id: string;
          created_at: string | null;
        };
        Insert: {
          id?: string;
          poll_id: string;
          question_id: string;
          option_id: string;
          user_id: string;
          created_at?: string | null;
        };
        Update: {
          id?: string;
          poll_id?: string;
          question_id?: string;
          option_id?: string;
          user_id?: string;
          created_at?: string | null;
        };
      };
      meeting_attendance_snapshots: {
        Row: {
          id: string;
          meeting_id: string;
          user_id: string;
          user_full_name: string;
          user_email: string;
          user_role: string;
          user_avatar_url: string | null;
          attendance_status: string;
          attendance_marked_by: string | null;
          attendance_marked_at: string | null;
          meeting_date: string;
          meeting_title: string;
          meeting_number: string | null;
          is_attendance_open: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          user_id: string;
          user_full_name: string;
          user_email: string;
          user_role: string;
          user_avatar_url?: string | null;
          attendance_status?: string;
          attendance_marked_by?: string | null;
          attendance_marked_at?: string | null;
          meeting_date: string;
          meeting_title: string;
          meeting_number?: string | null;
          is_attendance_open?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          user_id?: string;
          user_full_name?: string;
          user_email?: string;
          user_role?: string;
          user_avatar_url?: string | null;
          attendance_status?: string;
          attendance_marked_by?: string | null;
          attendance_marked_at?: string | null;
          meeting_date?: string;
          meeting_title?: string;
          meeting_number?: string | null;
          is_attendance_open?: boolean;
          created_at?: string;
          updated_at?: string;
        };
      };
      grammarian_reports: {
        Row: {
          id: string;
          meeting_id: string;
          club_id: string;
          word_of_the_day: string | null;
          recorded_by: string;
          meeting_date: string | null;
          meeting_number: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          club_id: string;
          word_of_the_day?: string | null;
          recorded_by: string;
          meeting_date?: string | null;
          meeting_number?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          club_id?: string;
          word_of_the_day?: string | null;
          recorded_by?: string;
          meeting_date?: string | null;
          meeting_number?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      timer_reports: {
        Row: {
          id: string;
          meeting_id: string;
          club_id: string;
          speaker_name: string;
          speaker_user_id: string | null;
          speech_category: string;
          actual_time_seconds: number;
          actual_time_display: string;
          time_qualification: boolean;
          target_min_seconds: number | null;
          target_max_seconds: number | null;
          notes: string | null;
          recorded_by: string;
          recorded_at: string;
          summary_visible_to_members: boolean;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          meeting_id: string;
          club_id: string;
          speaker_name: string;
          speaker_user_id?: string | null;
          speech_category: string;
          actual_time_seconds: number;
          actual_time_display: string;
          time_qualification: boolean;
          target_min_seconds?: number | null;
          target_max_seconds?: number | null;
          notes?: string | null;
          recorded_by: string;
          recorded_at?: string;
          summary_visible_to_members?: boolean;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          meeting_id?: string;
          club_id?: string;
          speaker_name?: string;
          speaker_user_id?: string | null;
          speech_category?: string;
          actual_time_seconds?: number;
          actual_time_display?: string;
          time_qualification?: boolean;
          target_min_seconds?: number | null;
          target_max_seconds?: number | null;
          notes?: string | null;
          recorded_by?: string;
          recorded_at?: string;
          summary_visible_to_members?: boolean;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      grammarian_word_usage: {
        Row: {
          id: string;
          grammarian_report_id: string;
          member_user_id: string | null;
          member_name: string;
          usage_count: number | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          grammarian_report_id: string;
          member_user_id?: string | null;
          member_name: string;
          usage_count?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          grammarian_report_id?: string;
          member_user_id?: string | null;
          member_name?: string;
          usage_count?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      grammarian_good_usage: {
        Row: {
          id: string;
          grammarian_report_id: string;
          member_user_id: string | null;
          member_name: string;
          good_usage_text: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          grammarian_report_id: string;
          member_user_id?: string | null;
          member_name: string;
          good_usage_text?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          grammarian_report_id?: string;
          member_user_id?: string | null;
          member_name?: string;
          good_usage_text?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
      grammarian_suggestions: {
        Row: {
          id: string;
          grammarian_report_id: string;
          member_user_id: string | null;
          member_name: string;
          improper_use: string | null;
          suggestions: string | null;
          created_at: string | null;
          updated_at: string | null;
        };
        Insert: {
          id?: string;
          grammarian_report_id: string;
          member_user_id?: string | null;
          member_name: string;
          improper_use?: string | null;
          suggestions?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
        Update: {
          id?: string;
          grammarian_report_id?: string;
          member_user_id?: string | null;
          member_name?: string;
          improper_use?: string | null;
          suggestions?: string | null;
          created_at?: string | null;
          updated_at?: string | null;
        };
      };
    };
    app_agenda_management: {
      Row: {
        id: string;
        meeting_id: string;
        title: string;
        document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
        document_url: string | null;
        pdf_data: string | null;
        status: 'pending' | 'available';
        created_by: string;
        club_id: string;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        meeting_id: string;
        title: string;
        document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
        document_url?: string | null;
        pdf_data?: string | null;
        status?: 'pending' | 'available';
        created_by: string;
        club_id: string;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        meeting_id?: string;
        title?: string;
        document_type?: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
        document_url?: string | null;
        pdf_data?: string | null;
        status?: 'pending' | 'available';
        created_by?: string;
        club_id?: string;
        created_at?: string;
        updated_at?: string;
      };
    };
    app_minutes_management: {
      Row: {
        id: string;
        meeting_id: string;
        title: string;
        document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
        document_url: string | null;
        pdf_data: string | null;
        status: 'pending' | 'available';
        created_by: string;
        club_id: string;
        created_at: string;
        updated_at: string;
      };
      Insert: {
        id?: string;
        meeting_id: string;
        title: string;
        document_type: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
        document_url?: string | null;
        pdf_data?: string | null;
        status?: 'pending' | 'available';
        created_by: string;
        club_id: string;
        created_at?: string;
        updated_at?: string;
      };
      Update: {
        id?: string;
        meeting_id?: string;
        title?: string;
        document_type?: 'google_doc' | 'pdf_url' | 'pdf_file' | 'website_url';
        document_url?: string | null;
        pdf_data?: string | null;
        status?: 'pending' | 'available';
        created_by?: string;
        club_id?: string;
        created_at?: string;
        updated_at?: string;
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}